### ISSUE TITLE
CmdImpersonate.cs and PluginNoTP.cs Won't Compile

### ISSUE THREAD

**Issue by Enclusion** [ClassiCube/MCGalaxy-Plugins#1]

**Comment by UnknownShadow200** [comment]
What is in your logs/errors/compiler.log when compiling CmdImpersonate? It compiles without a problem for me.

**Comment by VirUs-23** [comment]
No i can compile but its not works :/
Plugin loaded successfully.
but i can tp
i made: /map motd -hax -push model=human -tp
what wrong?

**Comment by UnknownShadow200** [comment]
It doesn't check for -tp in motd, it is hardcoded to deny tp [based on map name](https://github.com/UnknownShadow200/MCGalaxy-Plugins/blob/master/PluginNoTP.cs#L20)

**Comment by VirUs-23** [comment]
???? ok and how?

**Comment by VirUs-23** [comment]
p.cancelcommand = true; change to p.cancelcommand = false; ?

**Comment by UnknownShadow200** [comment]
No, not cancelling the command means that /tp will still run.

You need to change:
```CSharp
static bool OnGameMap(string map) {
    return map.CaselessStarts("zs");
}
```
to
```CSharp
static bool CanUseTp(Level lvl) {
    return !lvl.Config.MOTD.CaselessContains("-hax");
}
```

and

```CSharp
if (OnGameMap(p.level.name)) {
...
if (OnGameMap(who.level.name)) {
```
to
```CSharp
if (CanUseTp(p.level)) {
...
if (CanUseTp(who.level)) {
```
```

**Comment by VirUs-23** [comment]
Thanks!

**Comment by VirUs-23** [comment]
### 

> `**

1. h

- [ ] 

**`

**Comment by UnknownShadow200** [comment]
Closing this due to no response
