### ISSUE TITLE
Compilation of MagicaVoxelImport fails

### ISSUE THREAD

**Issue by zibbozz** [ClassiCube/MCGalaxy-Plugins#2]
Using MCGalaxy 1.9.2.5 on Windows 10 64 Bit.

The error Im getting:

> Error #CS1061 on line 271 - 'MCGalaxy.Level' enthält keine Definition für 'SetExtTile', und es konnte keine Erweiterungsmethode 'SetExtTile' gefunden werden, die ein erstes Argument vom Typ 'MCGalaxy.Level' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).

It says there is no method named SetExtTile with the first argument of the type MCGalaxy.Level.

**Comment by zibbozz** [comment]
There are a few other plugins I cannot compile:

- BinVoxImport
- CmdBiggestTables
- CmdCopyServerMap

**Comment by UnknownShadow200** [comment]
CopyServerMap doesn't compile because I haven't finished it yet, others should compile now though

**Comment by zibbozz** [comment]
Everything is working now (except CopyServerMap of course). Thank you for your effort to fix it so fast :)
