### ISSUE TITLE
LockedModel

### ISSUE THREAD

**Issue by Faris90** [ClassiCube/MCGalaxy-Plugins#3]
How do I use LockedModel?

**Comment by Goodlyay** [comment]
You need to include a specific phrase in the MOTD of the map to determine which model(s) the player is forced to use.

For example: /map motd -hax +respawn model=humanoid

This makes the map only allow human model.

You can also add more than one allowed model by using commas. For example:
model=humanoid,zombie,skeleton

If you don't have permission to set map options, you can try /os map motd instead.

**Comment by Faris90** [comment]
Why does it not work /map main -hax +respawn model=1

**Comment by Faris90** [comment]
didn't work

**Comment by Faris90** [comment]
I still am humanoid
